# Generated by Django 4.2.3 on 2023-07-20 06:01

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=tasks.models.end_of_date),
        ),
    ]
